patchesStrategicMerge:
- deployment_patch.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- name: 708595888134.dkr.ecr.ap-northeast-2.amazonaws.com/jena-private
  newTag: "14"
