apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: kube-system
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30011
  type: NodePort   